### ISSUE TITLE
Cant Import data

### ISSUE THREAD

**Issue by DavidFerreira1002** [FedericoRollo/followme#4]
I did the "roslaunch followme followme.launch" and got this:

NODES
  /
    followme_node (followme/followme_node)
    target_node (target_estimation/target_node)
    track_person_node (followme/track_person_node.py)

auto-starting new master
process[master]: started with pid [13334]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to fbf97a04-c62a-11ee-8860-97550c58e1fb
process[rosout-1]: started with pid [13347]
started core service [/rosout]
process[track_person_node-2]: started with pid [13354]
process[target_node-3]: started with pid [13355]
process[followme_node-4]: started with pid [13356]
Traceback (most recent call last):
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/devel/lib/followme/track_person_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/followme/scripts/track_person_node.py", line 25, in <module>
    from ai_utils.detectors.YolactInference import YolactInference
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/ai_utils/ai_utils/detectors/YolactInference.py", line 24, in <module>
    from data import COLORS
ModuleNotFoundError: No module named 'data'

Is there anything Im missing?

**Comment by FedericoRollo** [comment]
Hi David,
Probably you haven't installed Yolact module correctly. 
Check it by typing ```pip list | grep yolact```. It should return Yolact with it's version and installation directory.

If the pip list returns empty just install Yolact as explained below.
Go in Yolact directory on the terminal and type:
```
Pip install -e .
```

The same could occur for MMT package ```pip list | grep yolact```. Go in the MMT directory and do the same command.

To be sure it is working check another time with the pip list.

**Comment by DavidFerreira1002** [comment]
got 

DCNv2                         0.1                  /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2
and
MMT                           1.1.0    

when I do "roslaunch followme followme.launch" it shows:

auto-starting new master
process[master]: started with pid [4547]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8af231cc-c62d-11ee-8633-21d0c291aa62
process[rosout-1]: started with pid [4560]
started core service [/rosout]
process[track_person_node-2]: started with pid [4567]
process[target_node-3]: started with pid [4568]
process[followme_node-4]: started with pid [4569]
Traceback (most recent call last):
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/devel/lib/followme/track_person_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/followme/scripts/track_person_node.py", line 25, in <module>
    from ai_utils.detectors.YolactInference import YolactInference
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/ai_utils/ai_utils/detectors/YolactInference.py", line 24, in <module>
    from data import COLORS
ModuleNotFoundError: No module named 'data'

**Comment by FedericoRollo** [comment]
As I said above, you don't have the reference to yolact directory in the pip server.

Open a terminal and type the following:
```
cd  /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact
pip install -e .
```

now if you type ```pip list | grep yolact``` you should see another line similar to:
```
yolact /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact
```

**Comment by DavidFerreira1002** [comment]
/Documents/Universidade/Tese/FollowMeFramework/src/yolact$ pip install -e .

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact

yolact does not have a setup.py, what do I do here to install it? create one? never did that, any tips?

**Comment by DavidFerreira1002** [comment]
I got the yolact installed thanks!

Now I cant seem to get the DCNv2 going tho,

Loading YOLACT model...Traceback (most recent call last):
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/devel/lib/followme/track_person_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/followme/scripts/track_person_node.py", line 127, in <module>
    yolact = YolactInference(model_weights=yolact_weights, display_img=display_img_results)
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/ai_utils/ai_utils/detectors/YolactInference.py", line 114, in __init__
    self.net = Yolact()
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/yolact.py", line 403, in __init__
    self.backbone = construct_backbone(cfg.backbone)
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/backbone.py", line 451, in construct_backbone
    backbone = cfg.type(*cfg.args)
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/backbone.py", line 83, in __init__
    self._make_layer(block, 128, layers[1], stride=2, dcn_layers=dcn_layers[1], dcn_interval=dcn_interval)
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/backbone.py", line 114, in _make_layer
    layers.append(block(self.inplanes, planes, stride, downsample, self.norm_layer, self.dilation, use_dcn=use_dcn))
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/backbone.py", line 22, in __init__
    self.conv2 = DCN(planes, planes, kernel_size=3, stride=stride,
  File "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/backbone.py", line 11, in DCN
    raise Exception('DCN could not be imported. If you want to use YOLACT++ models, compile DCN. Check the README for instructions.')
Exception: DCN could not be imported. If you want to use YOLACT++ models, compile DCN. Check the README for instructions.

so I tried to follow the instructions here [https://github.com/LeoBoticsHub/yolact](url), I did the env and tried there but Im getting:

<details>
  <summary> error text </summary>

running build
running build_ext
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
building '_ext' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/include -I/usr/include/python3.8 -c /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp -o build/temp.linux-x86_64-3.8/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp:2:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h: In function ‘at::Tensor dcn_v2_forward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, int, int, int, int, int, int, int)’:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h:25:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   25 |     if (input.type().is_cuda())
      |                    ^
In file included from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cpu/vision.h:2,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp:2:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
  194 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp:2:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h: In function ‘std::vector<at::Tensor> dcn_v2_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, int, int, int, int, int, int, int)’:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h:54:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   54 |     if (input.type().is_cuda())
      |                    ^
In file included from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cpu/vision.h:2,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp:2:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
  194 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp:2:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h: In function ‘std::tuple<at::Tensor, at::Tensor> dcn_v2_psroi_pooling_forward(const at::Tensor&, const at::Tensor&, const at::Tensor&, int, float, int, int, int, int, int, float)’:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h:88:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   88 |     if (input.type().is_cuda())
      |                    ^
In file included from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cpu/vision.h:2,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp:2:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
  194 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp:2:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h: In function ‘std::tuple<at::Tensor, at::Tensor> dcn_v2_psroi_pooling_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, float, int, int, int, int, int, float)’:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h:124:20: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
  124 |     if (input.type().is_cuda())
      |                    ^
In file included from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cpu/vision.h:2,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/dcn_v2.h:3,
                 from /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/vision.cpp:2:
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
  194 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/include -I/usr/include/python3.8 -c /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cpu/dcn_v2_cpu.cpp -o build/temp.linux-x86_64-3.8/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cpu/dcn_v2_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/usr/local/cuda-11.3/bin/nvcc -DWITH_CUDA -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/include -I/usr/include/python3.8 -c /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.cu -o build/temp.linux-x86_64-3.8/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
/usr/local/cuda-11.3/bin/nvcc -DWITH_CUDA -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/TH -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/david/Documents/Universidade/Tese/FollowMeFramework/src/env/include -I/usr/include/python3.8 -c /home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu -o build/temp.linux-x86_64-3.8/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu(107): error: identifier "THCState_getCurrentStream" is undefined

/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu(126): error: identifier "THCudaBlas_SgemmBatched" is undefined

/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu(273): error: identifier "THCudaBlas_Sgemm" is undefined

/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu(279): error: identifier "THCState_getCurrentStream" is undefined

/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu(324): error: identifier "THCudaBlas_Sgemv" is undefined

5 errors detected in the compilation of "/home/david/Documents/Universidade/Tese/FollowMeFramework/src/yolact/external/DCNv2/src/cuda/dcn_v2_cuda.cu".
error: command '/usr/local/cuda-11.3/bin/nvcc' failed with exit status 1

</details>

**Comment by DavidFerreira1002** [comment]
missclick sry

**Comment by FedericoRollo** [comment]
Mh... I never encountered this error.

Check what torch version you have installed on your PC ```pip list | grep torch```

If it fits with the one linked in ai_utils package then try uninstalling DCNv2 with ```pip uninstall DCNv2``` and then reinstall it with ```pip install -e .```

**Comment by DavidFerreira1002** [comment]
I noticed I was installing the DCNv2 but that one is outdated, I found a fork that had it updated and then I noticed it was already there but it was called DCNv2_latest, tried that and it installed well!

now its giving me this:

```
INFO - 2024-02-09 15:27:05,485 - topics - topicmanager initialized
/home/david/.local/lib/python3.8/site-packages/torch/jit/_recursive.py:234: UserWarning: 'lat_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
/home/david/.local/lib/python3.8/site-packages/torch/jit/_recursive.py:234: UserWarning: 'pred_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
/home/david/.local/lib/python3.8/site-packages/torch/jit/_recursive.py:234: UserWarning: 'downsample_layers' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
Loading YOLACT model...
The weight in /home/david/Documents/Universidade/Tese/FollowMeFramework/src/followme/weights/yola
ct_plus_resnet50_54_800000.pth does not exists. You must download them in that directory.
```

**Comment by FedericoRollo** [comment]
You have to create weights directory in followme
```
mkdir /home/david/Documents/Universidade/Tese/FollowMeFramework/src/followme/weights
```
and then download the yolact_plus_resnet50_54_800000.pth file and move it inside the weights directory. You can find such file download on yolact readme.

You also need other two weights files which you can find here:
https://drive.google.com/file/d/1-f9W-SBOL2-GtIZnIPgID9M8G3H0ulfs/view?usp=drive_link
https://drive.google.com/file/d/1AEf6usBBuKo7XRhTw9soe3HjY1SC6lBd/view?usp=drive_link

Move them in the same directory!

**Comment by DavidFerreira1002** [comment]
thanks! going to close this issue.
